/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.NhanVienDAO;
import entity.NhanVien;
import helper.SharedData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author ADMIN
 */
public class MainForm extends javax.swing.JFrame {

    private QLTaiKhoan_Form mTaiKhoan;
    private QLSanPham_Form mQLSP;
    private QLNhanVien_Form mQLNV;
    private QLKhachHang_Form mQLKH;
    private BanHang_Form mBanHang;
    private DonDatHang_Form mDatHang;
    private ThongKeDoanhThu_Form mTKDoanhThu;
    private ThongKeSanPham_Form mTKSanPham;
    private QLHoaDon_Form mQLHoaDon;
    private TimKiemNhanVien_Form mTimNV;
    private ThuocTinh_Form mThuocTinh;
    private ThongKeKhachHang_Form mTKKhachHang;
    private TimKiemKhacHang_Form mTimKH;
    private TimKiemSanPham_Form mTimSP;
    private NhanVienDAO nv_dao = new NhanVienDAO();

    /**
     * Creates new form QuanLyNhanVien
     */
    public MainForm() throws Exception {
        initComponents();
        setTitle("Quản lý cửa hàng thời trang NTD Shop");
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        processLoginSucessful();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        tbrLogout = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnBanHang = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnMuaHang = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLoginName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        tblMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        menuThoat = new javax.swing.JMenuItem();
        mnuSP = new javax.swing.JMenu();
        menuThemSP = new javax.swing.JMenuItem();
        mnuThuocTinh = new javax.swing.JMenuItem();
        mnuTimKimSP = new javax.swing.JMenuItem();
        mnuKH = new javax.swing.JMenu();
        mnuCapNhatKH = new javax.swing.JMenuItem();
        mnuTimKH = new javax.swing.JMenuItem();
        mnuNV = new javax.swing.JMenu();
        mnuBanHang = new javax.swing.JMenuItem();
        mnuDatHang = new javax.swing.JMenuItem();
        mnuThemNV = new javax.swing.JMenuItem();
        mnuTimNV = new javax.swing.JMenuItem();
        mnuTKSPham = new javax.swing.JMenuItem();
        mnuTKDThu = new javax.swing.JMenuItem();
        mnuTKKH = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuHoaDon = new javax.swing.JMenuItem();
        mnuTK = new javax.swing.JMenu();
        menuCapNhatTK = new javax.swing.JMenuItem();
        menuDoiPasss = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        tbrLogout.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        tbrLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-icon-16.png"))); // NOI18N
        tbrLogout.setText("Đăng Xuất");
        tbrLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLogout);
        jToolBar1.add(jSeparator4);

        btnBanHang.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/market.png"))); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBanHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBanHang);
        jToolBar1.add(jSeparator2);

        btnMuaHang.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnMuaHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cargo.png"))); // NOI18N
        btnMuaHang.setText("Đơn Hàng");
        btnMuaHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMuaHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMuaHang);
        jToolBar1.add(jSeparator5);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-help-about-icon-16.png"))); // NOI18N
        jButton4.setText("Trợ Giúp");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator7);

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NTD Fashion");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Tên NV:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Chức vụ: ");

        lblLoginName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblRole.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tblMain.setBackground(new java.awt.Color(51, 255, 153));

        jDesktopPane2.setLayer(tblMain, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblMain)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblMain, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );

        jMenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 255, 204))); // NOI18N
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/system.png"))); // NOI18N
        jMenu1.setText("Hệ Thống");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        mnuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-icon-16.png"))); // NOI18N
        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDangXuat);

        menuThoat.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        menuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Close-icon-16.png"))); // NOI18N
        menuThoat.setText("Thoát");
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        jMenu1.add(menuThoat);

        jMenuBar1.add(jMenu1);

        mnuSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/qa32.png"))); // NOI18N
        mnuSP.setText("Sản Phẩm");
        mnuSP.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        menuThemSP.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        menuThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        menuThemSP.setText("Cập nhật");
        menuThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemSPActionPerformed(evt);
            }
        });
        mnuSP.add(menuThemSP);

        mnuThuocTinh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuThuocTinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/them.png"))); // NOI18N
        mnuThuocTinh.setText("Thuộc tính");
        mnuThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThuocTinhActionPerformed(evt);
            }
        });
        mnuSP.add(mnuThuocTinh);

        mnuTimKimSP.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuTimKimSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-16.png"))); // NOI18N
        mnuTimKimSP.setText("Tra cứu");
        mnuTimKimSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTimKimSPActionPerformed(evt);
            }
        });
        mnuSP.add(mnuTimKimSP);

        jMenuBar1.add(mnuSP);

        mnuKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rating.png"))); // NOI18N
        mnuKH.setText("Khách Hàng");
        mnuKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        mnuCapNhatKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuCapNhatKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        mnuCapNhatKH.setText("Cập nhật");
        mnuCapNhatKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCapNhatKHActionPerformed(evt);
            }
        });
        mnuKH.add(mnuCapNhatKH);

        mnuTimKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuTimKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-16.png"))); // NOI18N
        mnuTimKH.setText("Tra cứu");
        mnuTimKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTimKHActionPerformed(evt);
            }
        });
        mnuKH.add(mnuTimKH);

        jMenuBar1.add(mnuKH);

        mnuNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nv32.png"))); // NOI18N
        mnuNV.setText("Nhân Viên");
        mnuNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        mnuBanHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBanHang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/market.png"))); // NOI18N
        mnuBanHang.setText("Bán hàng");
        mnuBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBanHangActionPerformed(evt);
            }
        });
        mnuNV.add(mnuBanHang);

        mnuDatHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuDatHang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuDatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cargo.png"))); // NOI18N
        mnuDatHang.setText("Đặt hàng");
        mnuDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDatHangActionPerformed(evt);
            }
        });
        mnuNV.add(mnuDatHang);

        mnuThemNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        mnuThemNV.setText("Cập nhật");
        mnuThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThemNVActionPerformed(evt);
            }
        });
        mnuNV.add(mnuThemNV);

        mnuTimNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuTimNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-16.png"))); // NOI18N
        mnuTimNV.setText("Tra cứu");
        mnuTimNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTimNVActionPerformed(evt);
            }
        });
        mnuNV.add(mnuTimNV);

        mnuTKSPham.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuTKSPham.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuTKSPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tksp16.png"))); // NOI18N
        mnuTKSPham.setText("Thống kê sản phẩm");
        mnuTKSPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTKSPhamActionPerformed(evt);
            }
        });
        mnuNV.add(mnuTKSPham);

        mnuTKDThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuTKDThu.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuTKDThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analysis.png"))); // NOI18N
        mnuTKDThu.setText("Thống kê doanh thu");
        mnuTKDThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTKDThuActionPerformed(evt);
            }
        });
        mnuNV.add(mnuTKDThu);

        mnuTKKH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuTKKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuTKKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/development.png"))); // NOI18N
        mnuTKKH.setText("Thống kê khách hàng");
        mnuTKKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTKKHActionPerformed(evt);
            }
        });
        mnuNV.add(mnuTKKH);

        jMenuBar1.add(mnuNV);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bill.png"))); // NOI18N
        jMenu6.setText("Hoá Đơn");
        jMenu6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        mnuHoaDon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-16.png"))); // NOI18N
        mnuHoaDon.setText("Tra cứu");
        mnuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHoaDonActionPerformed(evt);
            }
        });
        jMenu6.add(mnuHoaDon);

        jMenuBar1.add(jMenu6);

        mnuTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tk32.png"))); // NOI18N
        mnuTK.setText("Tài Khoản");
        mnuTK.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        menuCapNhatTK.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        menuCapNhatTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        menuCapNhatTK.setText("Cập nhật");
        menuCapNhatTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCapNhatTKActionPerformed(evt);
            }
        });
        mnuTK.add(menuCapNhatTK);

        menuDoiPasss.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        menuDoiPasss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/padlock.png"))); // NOI18N
        menuDoiPasss.setText("Thay đổi mật khẩu");
        menuDoiPasss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDoiPasssActionPerformed(evt);
            }
        });
        mnuTK.add(menuDoiPasss);

        jMenuBar1.add(mnuTK);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-help-about-icon-32.png"))); // NOI18N
        jMenu3.setText("Trợ Giúp");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem5.setText("Giới Thiệu");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuThoatActionPerformed

    private void mnuTimKimSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTimKimSPActionPerformed
        try {
            mTimSP = new TimKiemSanPham_Form();
            tblMain.removeAll();
            tblMain.addTab("Tìm kiếm sản phẩm", mTimSP);

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mTimSP);
    }//GEN-LAST:event_mnuTimKimSPActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnMuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaHangActionPerformed
               try {
            mDatHang = new DonDatHang_Form();
            tblMain.removeAll();
            tblMain.addTab("Quản lý đặt hàng", mDatHang);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mDatHang);
    }//GEN-LAST:event_btnMuaHangActionPerformed

    private void tbrLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLogoutActionPerformed
        DangNhap_Form a = new DangNhap_Form();
        a.setVisible(true);
        this.dispose();

        try {
            processLoginSucessful();
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbrLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            processLoginSucessful();
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void mnuThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThemNVActionPerformed
        try {
            mQLNV = new QLNhanVien_Form();
            tblMain.removeAll();
            tblMain.addTab("Quản lý nhân viên", mQLNV);

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mQLNV);
    }//GEN-LAST:event_mnuThemNVActionPerformed

    private void menuDoiPasssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDoiPasssActionPerformed
        DoiMatKhau_Form resetpass = new DoiMatKhau_Form(this, true);
        resetpass.setVisible(true);
    }//GEN-LAST:event_menuDoiPasssActionPerformed

    private void menuCapNhatTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCapNhatTKActionPerformed

        mTaiKhoan = new QLTaiKhoan_Form();

        tblMain.removeAll();
        tblMain.addTab("Quản lý tài khoản", mTaiKhoan);
        tblMain.setSelectedComponent(mTaiKhoan);
    }//GEN-LAST:event_menuCapNhatTKActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
                try {
            mBanHang = new BanHang_Form();

            tblMain.removeAll();
            tblMain.addTab("Quản lý bán hàng", mBanHang);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mBanHang);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void menuThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemSPActionPerformed

        try {
            mQLSP = new QLSanPham_Form();

            tblMain.removeAll();
            tblMain.addTab("Quản lý sản phẩm", mQLSP);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mQLSP);
    }//GEN-LAST:event_menuThemSPActionPerformed

    private void mnuTKDThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTKDThuActionPerformed

        try {
            mTKDoanhThu = new ThongKeDoanhThu_Form();
            tblMain.removeAll();
            tblMain.addTab("Thống kê doanh thu", mTKDoanhThu);

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mTKDoanhThu);
    }//GEN-LAST:event_mnuTKDThuActionPerformed

    private void mnuCapNhatKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCapNhatKHActionPerformed

        try {
            mQLKH = new QLKhachHang_Form();

            tblMain.removeAll();
            tblMain.addTab("Quản lý khách hàng", mQLKH);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mQLKH);
    }//GEN-LAST:event_mnuCapNhatKHActionPerformed

    private void mnuBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBanHangActionPerformed

        try {
            mBanHang = new BanHang_Form();

            tblMain.removeAll();
            tblMain.addTab("Quản lý bán hàng", mBanHang);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mBanHang);
    }//GEN-LAST:event_mnuBanHangActionPerformed

    private void mnuTKSPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTKSPhamActionPerformed

        try {
            mTKSanPham = new ThongKeSanPham_Form();

            tblMain.removeAll();
            tblMain.addTab("Thống kê sản phẩm", mTKSanPham);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mTKSanPham);

    }//GEN-LAST:event_mnuTKSPhamActionPerformed

    private void mnuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHoaDonActionPerformed
        try {
            mQLHoaDon = new QLHoaDon_Form();
            tblMain.removeAll();
            tblMain.addTab("Quản lý hoá đơn", mQLHoaDon);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mQLHoaDon);
    }//GEN-LAST:event_mnuHoaDonActionPerformed

    private void mnuTimNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTimNVActionPerformed
        try {
            mTimNV = new TimKiemNhanVien_Form();
            tblMain.removeAll();
            tblMain.addTab("Tìm kiếm nhân viên", mTimNV);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mTimNV);
    }//GEN-LAST:event_mnuTimNVActionPerformed

    private void mnuThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThuocTinhActionPerformed
        try {
            mThuocTinh = new ThuocTinh_Form();
            tblMain.removeAll();
            tblMain.addTab("Thuộc tính sản phẩm", mThuocTinh);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mThuocTinh);
    }//GEN-LAST:event_mnuThuocTinhActionPerformed

    private void mnuDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDatHangActionPerformed
        try {
            mDatHang = new DonDatHang_Form();
            tblMain.removeAll();
            tblMain.addTab("Quản lý đặt hàng", mDatHang);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mDatHang);
    }//GEN-LAST:event_mnuDatHangActionPerformed

    private void mnuTKKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTKKHActionPerformed
        try {
            mTKKhachHang = new ThongKeKhachHang_Form();
            tblMain.removeAll();
            tblMain.addTab("Thống kê khách hàng", mTKKhachHang);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mTKKhachHang);
    }//GEN-LAST:event_mnuTKKHActionPerformed

    private void mnuTimKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTimKHActionPerformed
        try {
            mTimKH = new TimKiemKhacHang_Form();
            tblMain.removeAll();
            tblMain.addTab("Tìm kiếm khách hàng", mTimKH);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblMain.setSelectedComponent(mTimKH);
    }//GEN-LAST:event_mnuTimKHActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
         DangNhap_Form a = new DangNhap_Form();
        a.setVisible(true);
        this.dispose();

        try {
            processLoginSucessful();
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void processLoginSucessful() throws Exception {
        String maTK = SharedData.nguoiDangNhap.getMaTK();

        NhanVien nv = nv_dao.getNhanVienTheoMaTK(maTK);
        lblLoginName.setText(nv.getHoTen());
        lblRole.setText(SharedData.nguoiDangNhap.getVaiTro());
        tblMain.removeAll();

        if (SharedData.nguoiDangNhap.getVaiTro().equals("Nhân viên")) {
            mnuTK.remove(menuCapNhatTK);
            mnuNV.remove(mnuTimNV);
            mnuNV.remove(mnuThemNV);
            mnuSP.remove(menuThemSP);
            mnuSP.remove(mnuThuocTinh);
//        } else if (SharedData.nguoiDangNhap.getVaiTro().equals("Quản lý")) {
//
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnMuaHang;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblLoginName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JMenuItem menuCapNhatTK;
    private javax.swing.JMenuItem menuDoiPasss;
    private javax.swing.JMenuItem menuThemSP;
    private javax.swing.JMenuItem menuThoat;
    private javax.swing.JMenuItem mnuBanHang;
    private javax.swing.JMenuItem mnuCapNhatKH;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDatHang;
    private javax.swing.JMenuItem mnuHoaDon;
    private javax.swing.JMenu mnuKH;
    private javax.swing.JMenu mnuNV;
    private javax.swing.JMenu mnuSP;
    private javax.swing.JMenu mnuTK;
    private javax.swing.JMenuItem mnuTKDThu;
    private javax.swing.JMenuItem mnuTKKH;
    private javax.swing.JMenuItem mnuTKSPham;
    private javax.swing.JMenuItem mnuThemNV;
    private javax.swing.JMenuItem mnuThuocTinh;
    private javax.swing.JMenuItem mnuTimKH;
    private javax.swing.JMenuItem mnuTimKimSP;
    private javax.swing.JMenuItem mnuTimNV;
    public static javax.swing.JTabbedPane tblMain;
    private javax.swing.JButton tbrLogout;
    // End of variables declaration//GEN-END:variables
}
